<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RemoteAppTool.Core\RemoteAppTool.Core.csproj" />
    <ProjectReference Include="..\RemoteAppTool.RdpFileLib\RemoteAppTool.RdpFileLib.csproj" />
    <ProjectReference Include="..\RemoteAppTool.SignLib\RemoteAppTool.SignLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
